- name: System Reboot activities
     hosts: all
     become: yes
     tasks:

            - name: task to update
              apt:
               only_upgrade: true


            - name: Restart server
              command: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
              async: 1
              poll: 0
              ignore_errors: true

            - name: Wait for port 22 to be available
              delegate_to: localhost
              wait_for:
                port: 22
                host: '{{ inventory_hostname }}'
                delay: 30
