apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datacenter
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
   spec:
    template:
     spec:
      containers:
            - name: cron-datacenter
              image: httpd:latest
              command:
                 - echo Welcome to xfusioncorp!
      restartPolicy: OnFailure