apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: pod-a-namespace
spec:
  containers:
  - name: pod-a
    image: nginx
    resources:
      limits:
        memory: "400M"
      requests:
        memory: "200M"


---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: pod-b-namespace
spec:
  containers:
  - name: pod-b
    image: httpd
    resources:
      limits:
        memory: "200M"
      requests:
        memory: "100M"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  namespace: pod-c-namespace
spec:
  containers:
  - name: pod-c
    image: busybox:latest
    resources:
      limits:
        memory: "400M"
      requests:
        memory: "200M"