apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2022-12-07T20:25:09Z"
    name: developer-rolebinding
    namespace: development
    resourceVersion: "4991"
    uid: 0d912c66-eee2-42de-9578-732f314d02c9
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: developer-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: martin
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""